version: 0.2
phases:
   install:
     runtime-versions:
         php: 8.1
        #  nodejs: 12.x
     commands:
         - apt-get update -y
         # - curl -sS <https://getcomposer.org/installer> | php -- --install-dir=/usr/local/bin --filename=composer

         #Install composer
         - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
         - php composer-setup.php ;
         - php -r "unlink('composer-setup.php');" ;
         - mv composer.phar /usr/local/bin/composer
   pre_build:
     commands:
        #  - cp .env.example .env
         - composer install
        #  - npm install
   build:
     commands:
         - echo "We are in the build block"
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes