version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  eb: circleci/aws-elastic-beanstalk@2.0.1

# Define the jobs we want to run for this project
jobs:
  aws-cli-cred-setup:
      executor: aws-cli/default
      steps:
        - aws-cli/setup:
            aws-access-key-id: AWS_ACCESS_KEY
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            aws-region: AWS_REGION_NAME
  build:
    docker:
      - image: cimg/php:8.1.12

    working_directory: ~/repo
    # branches:
    #    only:
    #      - circleci
    steps:
      - checkout
      - run: sudo docker-php-ext-install zip
          # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # Install software required to run EB deployer
      # - run:
      #     name: Installing deployment dependencies
      #     working_directory: ~/repo
      #     command: |
      #       sudo apt-get install python3
      #       curl -O https://bootstrap.pypa.io/get-pip.py
      #       python3 get-pip.py
      #       pip install awsebcli --upgrade

       # Add everything (except vendors that will be installed automatically and node_modules that are not needed because we already built js and css) to a ZIP
      - run:
          name: ZIP project
          working_directory: ~/repo
          command: zip test_project.zip -r * .[^.]* --exclude=vendor/* --exclude=node_modules/* --exclude=.circleci/* --exclude=.elasticbeanstalk/*
      # - run:
      #     name: Deploy project
      #     #command: eb deploy --staged prod_env
      #     command: eb deploy
  deploy:
    docker:
        - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          name: Deploy project
          command: eb deploy

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - aws-cli-cred-setup:
          context: aws
      - build:
          requires:
            - aws-cli-cred-setup
      - deploy:
          requires:
            - build
